@{
    Extensions = @(
        "ms-vscode.powershell"
        "Catppuccin.catppuccin-vsc"
        "Catppuccin.catppuccin-vsc-icons"
        "usernamehw.errorlens"
        "tamasfe.even-better-toml"
        "TheNuProjectContributors.vscode-nushell-lang"
        "openai.chatgpt"
        "esbenp.prettier-vscode"
        "yzhang.markdown-all-in-one"
        "ms-dotnettools.csdevkit"
        "github.vscode-github-actions"
        "rodrigovallades.es7-react-js-snippets"
        "bradlc.vscode-tailwindcss"
        "heybourn.headwind"
        "dbaeumer.vscode-eslint"
    )
}
